name: Deploy

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: get deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: build lume site
        run: cd v2022 && deno task build

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "garn-dev" # the name of the project on Deno Deploy
          entrypoint: "./serve.tsx" # the entrypoint to deploy
          import-map: "./import_map.json" # the import map to use
          # root: "."