name: Deploy
on:
  schedule:
    - cron: '0 0 1 * *' # Runs at 00:00 on the 1st of every month
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      # - name: Install Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '22'

      # - name: Install Puppeteer dependencies
      #   run: sudo apt-get install -y libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxkbcommon-x11-0 libxcomposite1 libxrandr2 libgbm1 libpango-1.0-0 libpangocairo-1.0-0

      # - name: Install Puppeteer
      #   run: npm install puppeteer

      - run: deno task fetchRepos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: deno task captureScreenshots

      - name: Commit screenshots
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add screenshots/
          git commit -m "Update screenshots" || echo "No changes to commit"
          git push || echo "No changes to commit"

      - name: Build step
        run: "deno task build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "garn-dev"
          entrypoint: "jsr:@std/http/file-server"
          root: "./_site"
